version: "3.8"

services:
  ehr-db:
    image: mongo
    container_name: ehr-db
    environment:
      - MONGO_INITDB_DATABASE=ehrdb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    restart: unless-stopped
    ports:
      - 27099:27017
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - ehr_db_network

  ehr-mongodb-express:
    image: mongo-express
    container_name: ehr-mongodb-express
    restart: unless-stopped
    ports:
      - 8099:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=ehr-db
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - ehr-db
    networks:
      - ehr_db_network
volumes:
  ehr_db_data:
    name: ehr_db_data
networks:
  ehr_db_network:
    name: ehr_db_network